[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "NHLPy"
version = "0.0.1"
authors = [
    {name="Corey Schaf", email="cschaf@gmail.com"}
]
description = "NHL API Wrapper"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[pyproject.optional-dependencies]
test = [
    "pytest >=7.1.3,<8.0.0",
    "coverage[toml] >= 6.5.0,< 8.0",
    "mypy ==0.982",
    "ruff ==0.0.138",
    "black == 23.1.0",
    "httpx >=0.23.0,<0.24.0"
]

all = [
    "httpx >=0.23.0"
]